name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installing Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache-dependency-path: interactive3DMerkaba/yarn.lock
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Build # (1) install, (2) bundle packages, (3) build apps
        working-directory: ./interactive3DMerkaba
        run: | 
          yarn install     
          yarn run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./interactive3DMerkaba/dist # The folder the action should deploy.
